# .travis.yml

sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install --local luaunit 2.1
  - luarocks install --local mockagne 1.0
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - luacheck --std max+busted *.lua spec
  - busted --verbose --coverage
  - cd unittests
  - $LUA gs-core.lua


after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install


notifications:
  email:
    on_failure: always
    on_success: change
