# .travis.yml
language: python
sudo: true

env:
  - LUA="lua=5.1" LUAC="luac5.1"

addons:
  apt:
    packages:
      - liblua5.1-bitop0

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install mockagne 1.0
  - luarocks install luaunit
  - luarocks install luabitop
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - luacheck --std max+busted --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences GS-Core/startup.lua
  - luacheck --std max+busted --globals seterrorhandler currentclassDisplayName GS-Core/errorhandler.lua
  - luacheck --std max+busted --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences GS-Core/Core.lua
  - luacheck --std max+busted --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences GS-SequenceEditor/editor-core.lua
  - luacheck --std max+busted --globals GSDebugOutput GSMasterOptions GSStaticSequenceDebug GSPrintDebugMessage GSisEmpty format GSCore Sequences GS-DraikMacros/Macros/*.lua
  - pwd
  - busted --verbose --coverage

after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install

notifications:
  email:
    on_failure: always
    on_success: change

cache:
  apt: true
  directories:
    - $HOME/.luarocks
